# This is a basic workflow that is manually triggered

name: Build and deploy docs

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  release:
    types: [published]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-env:
    name: Build and deploy docs to website
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    artifacts:
      untracked: true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r docs/requirements.txt
        python -m pip install .
        python -m pip install -r docs/source/notebooks/requirements.txt

    - name: Install Pandoc
      run: |
        sudo apt update
        sudo apt install pandoc

  running-notebooks:
    name: Rerunning notebook ${{ matrix.notebook }}
    dependencies:
      - build-env
    if: always()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebook: ["2-modeGroveralgorithm.ipynb", "Reinforcementlearning.ipynb", "BS-basedimplementationnotebook.ipynb", "Remotecomputing.ipynb", "BosonSamplingwithMPS.ipynb", "RewritingrulesinPerceval.ipynb", "BosonSampling.ipynb", "ShorImplementation.ipynb", "Differentialequationsolving.ipynb", "Tutorial.ipynb", "GraphStatesandrepresentation.ipynb", "VariationalQuantumEigensolver.ipynb", "Non-unitarycomponents.ipynb", "QUBO.ipynb", "walkthrough-cnot.ipynb", "Qiskitconversion.ipynb"]
    steps:
    - name: Rerunning notebook ${{ matrix.notebook }}
      run: |
        cd docs/source/notebooks/
        jupyter nbconvert --clear-output --inplace "${{ matrix.notebook }}"
        jupyter nbconvert --execute --to notebook "${{ matrix.notebook }}"
      artifacts:
        untracked: docs/source/notebooks/${{ matrix.notebook }}

    - name: Build docs
      run: |
        cd docs
        make html

  build-doc:
    name: Build and deploy docs to website
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    dependencies:
      - build-env
      - running-notebooks
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r docs/requirements.txt
        python -m pip install .
        python -m pip install -r docs/source/notebooks/requirements.txt

    - name: Install Pandoc
      run: |
        sudo apt update
        sudo apt install pandoc